#################
### Load data ###
#################

rm(list=setdiff(ls(),c('params','grp','injection.site','goi','probe')))
print(grp)
basedir <- params$basedir
setwd(basedir)
savedir <- paste(params$opdir,'diffmodel/bidirectional/',paste0(injection.site,collapse='-'),'/',sep='')
dir.create(savedir,recursive=T)

source('code/misc/fitfxns.R')
source('code/misc/miscfxns.R')
source('code/misc/plottingfxns.R')
load(paste(params$opdir,'processed/pathdata.RData',sep=''))  # load path data and ROI names
load(paste(savedir,grp,'CNDRSpaceBidirectionalOptim_data.RData',sep=''))
tps <- params$tps
col <- getGroupColors(params$grps)[grp] # get color for plots

# exclude regions with 0 pathology at each time point for purposes of computing fit
lapply(1:length(tps), function(t) paste0(t,' MPI: ',sum(df[[t]]$path != -Inf & !is.na(df[[t]]$pred.retro)),'/',nrow(df[[t]]),' regions left'))

##########################################################
### add together anterograde and retrograde prediction ###
##########################################################

# m is linear regression model objects that combine anterograde and retrograde predictions at each time point
# generated by code/diffmodel/optim_bidirectionalspread_CNDRspace.R
vulnerability <- lapply(m,residuals)
pred <- lapply(m, function(m.i) m.i$fitted.values)

# separately show retrograde and anterograde contributions to fit
m.std <- lapply(m,lm.beta) # get standardized betas to compare
m.vif <- max(sapply(m,vif))
ant.ret.betas <- cbind(tps,do.call(rbind,lapply(m.std, function(m.i) c(Overall=sqrt(summary(m.i)$r.square),
                                                                       m.i$standardized.coefficients[c('pred.antero','pred.retro')]))))
colnames(ant.ret.betas) <- c('MPI','Overall','Anterograde','Retrograde')
df.plt <- collapse.columns(as.data.frame(ant.ret.betas,stringsAsFactors = F),cnames=c('Overall','Anterograde','Retrograde'),groupby='MPI')
p <- ggplot(df.plt) + geom_line(aes(x=group,y=values,color=names),alpha=0.5) + geom_point(aes(x=group,y=values,color=names)) +
  scale_color_brewer(palette='Set2',breaks=c('Overall','Anterograde','Retrograde')) + scale_x_continuous(breaks=tps,labels=paste(tps,'MPI')) + 
  scale_y_continuous(limits=c(0,NA)) + theme_bw() + 
  xlab('') + ylab('Standardized Beta') + ggtitle(paste('Max VIF:',signif(m.vif,2))) + theme(text=element_text(size=8),legend.title = element_blank(),plot.title=element_text(size=8,hjust=0.5))
ggsave(p,filename = paste(savedir,grp,'CNDRSpaceFitAnteroRetroBetas_bidirectionaladditivemodel.pdf',sep=''),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

p <- lapply(1:length(tps), function(t) 
  p.xy(x=m[[t]]$fitted.values,y=m[[t]]$model$path,ylab='Actual',xlab='Predicted',
       ttl=paste0(grp,': ',tps[t],' MPI'),col=col,alpha=0.7))
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste(savedir,grp,'CNDRSpaceFit_bidirectionaladditivemodel.pdf',sep=''),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# plot fit and separately display hemispheres

p <- lapply(1:length(tps), function(t) 
  p.xyc(x=m[[t]]$fitted.values,y=m[[t]]$model$path,ca=substr(names(m[[t]]$fitted.values),1,1),ylab='Actual',xlab='Predicted',
       ttl=paste0(grp,': ',tps[t],' MPI'),col=col,alpha=0.7) + 
    theme(legend.position = c(0.1,1),legend.background=element_blank(),legend.key.size = unit(0.1, "cm"),legend.title = element_blank()))
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste(savedir,grp,'CNDRSpaceFitHemiColor_bidirectionaladditivemodel.pdf',sep=''),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# initialize empty data frame with all CNDR regions and time points
df.vuln <- df.pred <- data.frame(matrix(ncol=length(tps),nrow=n.regions.CNDR, dimnames=list(path.names, paste(tps,'MPI'))),check.names = FALSE)
for(t in 1:length(tps)){
  regions.mpi <- names(vulnerability[[t]]) # get the regions that had non-zero pathology at each tp (so log can be computed)
  df.vuln[regions.mpi,paste(tps[t],'MPI')] <- vulnerability[[t]][regions.mpi]
  df.pred[regions.mpi,paste(tps[t],'MPI')] <- pred[[t]][regions.mpi]
}

# compute intrinsic vulnerability as an average over time and hemispheres
tp.excl <- '1 MPI' # exclude 1 MPI - see diffmodel/vuln_hemi_time.R
hemi.average.vuln <- hemi.average(df.vuln[,-which(colnames(df.vuln)==tp.excl)])
write.csv(hemi.average.vuln,paste0(savedir,grp,'vulnerability_bidirectional_hemiaverage_exclude',tp.excl,'.csv'))

write.csv(df.vuln,paste0(savedir,grp,'vulnerability_bidirectional.csv')) # save vulnerability for each time point

write.csv(df.pred,paste0(savedir,grp,'log10predictedpath_bidirectional.csv')) # save log10 predicted path

#####################
### Add gene data ###
#####################

# load gene data specified by goi, probe input variables
gene.exp <- read.csv(paste0(basedir,'data/aba/expression/',goi,probe,'ExpressionCNDR.csv'),row.names = 1)
df.gene <- lapply(df, function(x) merge(x,gene.exp,by=0)) # merge with pathology data frame
for(j in 1:length(df.gene)){rownames(df.gene[[j]]) <- df.gene[[j]]$Row.names} # remove row names
for(j in 1:length(df.gene)){df.gene[[j]] <- df.gene[[j]][,-1]}

##########################################################################
### show how gene expression correlates with residuals of spread model ###
##########################################################################

vuln.gene <- lapply(vulnerability, function(v) merge(as.data.frame(v),gene.exp,by=0))
p <- lapply(1:length(tps), function(t)
  p.xy(x=vuln.gene[[t]][,paste0(goi,'_',probe)],y=vuln.gene[[t]]$v,ylab='Vulnerability',xlab=paste0(goi,' Expression'),
       ttl=paste0(grp,': ',tps[t],' MPI'),col=col,alpha=0.7))
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste(savedir,grp,'CNDRSpaceVulnerability_bidirectionalmodel_vs',goi,probe,'.pdf',sep=''),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# look at hemisphere average vulnerability
hemi.average(gene.exp)
p <- p.xy(x=hemi.average(gene.exp)$v,y=hemi.average.vuln$v,ylab='Vulnerability',xlab=paste0(goi,' Expression'),
       ttl=paste0(grp,': ',tps[t],' MPI'),col=col,alpha=0.7)
ggsave(p,filename = paste(savedir,grp,'CNDRSpaceHemiAverageVulnerability_Exclude',tp.excl,'_bidirectionalmodel_vs',goi,probe,'.pdf',sep=''),
       units = 'cm',height = 3.75,width = 3.75,useDingbats=FALSE)

##############################
### Include genes in model ###
##############################

m <- lapply(df.gene, function(df.i) m <- lm(path~.,data=inf.nan.mask(df.i)))
vulnerability <- lapply(m,residuals)
pred <- lapply(m, function(m.i) m.i$fitted.values)

p <- lapply(1:length(tps), function(t)
  p.xy(x=m[[t]]$fitted.values,y=m[[t]]$model$path,ylab='Actual',xlab='Predicted',
       ttl=paste0(grp,': ',tps[t],' MPI'),col=col,alpha=0.7))
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste(savedir,grp,'CNDRSpaceFit_bidirectionalmodel+',goi,probe,'.pdf',sep=''),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# concatenate predicted path (fitted vals, y-hat) and vulnerability (residuals, y-yhat) into one dataframe
# initialize empty data frame with all CNDR regions and time points
df.vuln <- df.pred <- data.frame(matrix(ncol=length(tps),nrow=n.regions.CNDR, dimnames=list(path.names, paste(tps,'MPI'))),check.names = FALSE)
for(t in 1:length(tps)){
  regions.mpi <- names(vulnerability[[t]]) # get the regions that had non-zero pathology at each tp (so log can be computed)
  df.vuln[regions.mpi,paste(tps[t],'MPI')] <- vulnerability[[t]][regions.mpi]
  df.pred[regions.mpi,paste(tps[t],'MPI')] <- pred[[t]][regions.mpi]
}

write.csv(hemi.average(df.vuln),paste0(savedir,grp,'vulnerability_bidirectional',goi,probe,'_hemiaverage.csv'))
df.vuln <- cbind(df.vuln,Average=rowMeans(df.vuln,na.rm = T)) # compute average vulnerability across time points, ignoring regions with 0 path
write.csv(df.vuln,paste0(savedir,grp,'vulnerability_bidirectional',goi,probe,'.csv'))
write.csv(df.pred,paste0(savedir,grp,'predictedpath_bidirectional',goi,probe,'.csv'))